### ISSUE TITLE
how about streaming?

### ISSUE THREAD

**Issue by soliton4** [75lb/handbrake-js#11]
i need to stream video data as h265 encoded.
is this possible?

**Comment by 75lb** [comment]
it's possible to stream video data, yes - but not using this library alone.. you use this library to create your h265 files, then use a separate solution to stream that video.. streaming is beyond the scope of handbrake-js.

**Comment by soliton4** [comment]
i am having trouble with h265 streaming. could you give me some help?

**Comment by 75lb** [comment]
i don’t know much about streaming, sorry..
