### ISSUE TITLE
Invalid downloadPath for 0.10.2 handbrake exe

### ISSUE THREAD

**Issue by dlbrown06** [75lb/handbrake-js#14]
![image](https://cloud.githubusercontent.com/assets/4063363/12620442/51a6f184-c4ea-11e5-864b-ced941fb5cd8.png)

This is failing because this is an invalid download location...

var downloadPath = 'https://handbrake.fr/rotation.php?file=HandBrake-0.10.2-%s'

**Comment by 75lb** [comment]
ugh, ok thanks.. it's because they host the binaries themselves and mercilessly delete old versions with each release.. 

will fix within the next couple of hours..

**Comment by dlbrown06** [comment]
Invalid URL that is current in the released code:
https://handbrake.fr/rotation.php?file=HandBrake-0.10.2-x86_64-Win_CLI.zip

Valid URL path
http://download.handbrake.fr/releases/0.10.2/HandBrake-0.10.2-x86_64-Win_CLI.zip <-- Valid

**Comment by dlbrown06** [comment]
lol thanks

**Comment by 75lb** [comment]
fix and released in v2.0.8, thanks again :+1:
