### ISSUE TITLE
Install fails due to HandBrake version release

### ISSUE THREAD

**Issue by steve-p-com** [75lb/handbrake-js#15]
We love handbrake-js and it's a vital part of an upcoming web service we are piloting to transcode user videos to universal formats.

I tried to install handbrake-js on a new development Mac yesterday, and unfortunately, it failed. It tries to download version 0.10.2 of HandBrake/HandBrakeCLI from handbrake.fr, but recently (Friday 22 January) version 0.10.3 was released and 0.10.2 is no longer available there. I expect Windows installs may also be broken.

**Comment by 75lb** [comment]
this was [fixed and released yesterday](https://github.com/75lb/handbrake-js/issues/14) but thank you for letting me know!

**Comment by 75lb** [comment]
the new version uses more stable/reliable download URLs, so sudden-url-changes won't be a problem again.

**Comment by steve-p-com** [comment]
Awesome, thanks. I looked yesterday for a reported issue but forgot to re-check this morning before creating one :blush: :
