### ISSUE TITLE
Playing video using Videojs player gives error

### ISSUE THREAD

**Issue by codeismine** [75lb/handbrake-js#22]
Hi There!

Hope you are doing great! We are facing one issue that When video is encoded using handbrake UI than Videojs player is able to play it without any issue. But when its encoded using nodejs, am getting error that "the media could not be loaded, either because the server or network failed or because the format is not supported"

Code:

 hbjs.spawn({
        input: videoTempDest,
        output: transcodedVideoDest,
        encoder: "x264",
        preset: 'Super HQ 1080p30 Surround'
    })
        .on("end", function (err) {

        })
        .on("error", function (err) {
            // invalid user input, no video found etc
            console.log("Transcode error: " + err)
        })
        .on("progress", function (progress) {
            console.log(
                "Percent complete: %s, ETA: %s",
                progress.percentComplete,
                progress.eta
            )
        })

Video url: 
https://assets.onfriday.tv/videos/movie/trailer-reaction/en-US/kush747@gmail.com/Power-Rangers-923d2bda-246f-4bb5-9982-a431dab8a6d9.mp4

Request you to please let me know if I am doing something wrong in this? Thanks!

**Comment by 75lb** [comment]
hi! It looks like you are using a Handbrake v1 preset ("Super HQ 1080p30 Surround") - this module currently uses version 0.10.5 and does not support that preset.. 

I'll close this ticket and open a new one to upgrade to Handbrake v1.0.0

**Comment by codeismine** [comment]
Hi,

Even preset:Normal is giving same issue.

-Thanks and Regards,
Jitesh Lalwani

On 24-Jan-2017 1:15 AM, "Lloyd Brookes" <notifications@github.com> wrote:

hi! It looks like you are using a Handbrake v1 preset ("Super HQ 1080p30
Surround") - this module currently uses version 0.10.5 and does not support
that preset..

I'll close this ticket and open a new one to upgrade to Handbrake v1.0.0

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/75lb/handbrake-js/issues/22#issuecomment-274595907>,
or mute
the thread
