### ISSUE TITLE
Does not work on Electron prod build

### ISSUE THREAD

**Issue by jpangelle** [75lb/handbrake-js#34]
Using `hbjs.spawn` in Electron dev environment works fine, but with the built Electron prod app, it goes to the `.on('error')` block. I've written the error message to a file:

```
  "err": {
    "message": "spawn ENOTDIR",
    "name": "InvalidOption",
    "output": "",
    "options": {
      "input": <valid-file-path>,
      "preset": "General/Fast 1080p30",
      "output": <valid-file-path>
    }
  }
```

Has anyone else used this library in an Electron prod build?

**Comment by 75lb** [comment]
Hi, I'll have a go a reproducing this tonight..

**Comment by jpangelle** [comment]
I got it working. There were a few things I needed to change. I will just document it here in case anyone in the future has problems using this library with Electron.

1. So, I had to change `this.cp.spawn` to `exec`, but first I had to reconstruct the command string to make sure it had quotes around my preset which has a space in it. Don't forget to `const { exec } = require('child_process');` at the top of the file. You can see my changes [here](https://github.com/jpangelle/handbrake-js/commit/88f035806a1653000f4f91aad2e51e4d1bd06df5).

2. For a reason that I do not quite understand yet but found on some StackOverflow posts is that you need to do a regex replace `'app.asar'` to `'app.asar.unpacked'`. You can see my implementation [here](https://github.com/jpangelle/handbrake-js/commit/df8f889f061ac0655845dacae262c8e4340073b3).

As far as I know, these are both Electron production-build specific problems/solutions. Feel free to contact me if you have issues. Thanks again to @75lb for such a great library! 🎉

**Comment by 75lb** [comment]
Cool, thanks for documenting the workaround.

1. Would it be easier to use [the handbrake-js exec() method](https://github.com/75lb/handbrake-js#hbjsexecoptions-oncomplete)?

**Comment by akcware** [comment]
@jpangelle Thanks for code, I was researching for 5 days and never find a way. But your exec function didn't worked me. So I did below.

Your code: 
```  
this._emitStart()

const newHandbrakeCLIPath = this.HandbrakeCLIPath.replace('app.asar', 'app.asar.unpacked');
const newCommand = `${newHandbrakeCLIPath} ${spawnArgs[0]} ${spawnArgs[1].split('=')[0]}='General/Fast 1080p30' ${spawnArgs[2]}`
 const handle = exec(newCommand);
```

My code:
```
this._emitStart()
const newHandbrakeCLIPath = this.HandbrakeCLIPath.replace('app.asar', 'app.asar.unpacked');
const handle = this.cp.spawn(newHandbrakeCLIPath, spawnArgs)
```

The important point was replacing app.asar to app.asar.unpacked. If someone had this problem, he can use my code.
