### ISSUE TITLE
Progress event not working

### ISSUE THREAD

**Issue by Ahnteve** [75lb/handbrake-js#36]
my code:
```
hbjs.spawn({ input: 'source.mpg', output: target.mp4', preset : 'Universal' })
    .on('progress', progress => {
      console.log(
        'Percent complete: %s, ETA: %s',
        progress.percentComplete,
        progress.eta
      )
    })
    .on('complete', () => {
      console.log('complete');
    });
```

log:
```
0|www    | Percent complete: 2.17, ETA:
PM2      | App [www:0] exited with code [1] via signal [SIGINT]
PM2      | pid=9256 msg=process killed
```

I think the log should be written like this.
```
0|www    | Percent complete: 2.17, ETA:
0|www    | Percent complete: 5.63, ETA:
0|www    | Percent complete: 8.42, ETA:
0|www    | Percent complete: 13.34, ETA:
more ...
```

Do you know why it works like this way? Did I write it wrong?

**Comment by 75lb** [comment]
Hi, sorry for the slow reply. I can't reproduce this, is it still an issue? If so, could you post instructions how to reproduce please.

**Comment by Ahnteve** [comment]
I upload a MPG video from a client. The server takes the video path, converts it into MP4 video, and uploads it to the 'upload' folder. The file is created, but the file is corrupt.

**Comment by Ahnteve** [comment]
I'm sorry to bother you.

my code:
![2](https://user-images.githubusercontent.com/33370010/51093758-1abeaa80-17ea-11e9-83c1-4d21ef8dd895.PNG)
files.videofile.path = C:\Users\USERNAME~1\AppData\Local\Temp\upload_030f5648b41c5f0153f4e30f9765c2bc


log: 
![1](https://user-images.githubusercontent.com/33370010/51093726-e1863a80-17e9-11e9-93f5-2f82ddbf79cf.PNG)

I think the reason it doesn't work is because it doesn't have an extension. ....
