### ISSUE TITLE
Piping/Output

### ISSUE THREAD

**Issue by BubbaJoe** [75lb/handbrake-js#39]
Is it possible pipe input or output for live streaming?

**Comment by cusspvz** [comment]
@75lb can you please reopen? You'd actually need to do changes on this lib in order to support NodeJS Streams to the Handbreak stdin and stdout.

**Comment by 75lb** [comment]
@cusspvz does HandbrakeCLI support streaming to and from stdin and stdout? If not, then handbrake-js will not support this either. This lib is just a Javascript interface to the existing CLI.
