### ISSUE TITLE
Where does HandbrakeCLI output error logs?

### ISSUE THREAD

**Issue by ImSeaWorld** [75lb/handbrake-js#40]
Running Windows 10 Pro 1803

Been getting this error trying to encode an AVI file.

`Other: Handbrake InitialisationError [error code: 3]`

I've checked the usual spot in Roaming, but there was only data for Handbrake GUI. 
So where does this output in depth error logs?

**Comment by 75lb** [comment]
I'm sorry, I really don't know where `HandbrakeCLI` writes error logs..
