### ISSUE TITLE
Error: Cannot find module 'child_process'

### ISSUE THREAD

**Issue by pk936** [75lb/handbrake-js#42]
When I run below code to convert avi file to other format, I got this error.

 
```
const hbjs = require('handbrake-js')
hbjs.spawn({ input: 'http://www.engr.colostate.edu/me/facil/dynamics/files/drop.avi', output: 'something.m4v' })
  .on('error', err => {
    // invalid user input, no video found etc
  })
  .on('progress', progress => {
    console.log(
      'Percent complete: %s, ETA: %s',
      progress.percentComplete,
      progress.eta
    )
  })
```

**Comment by 75lb** [comment]
what version of node are you using? Which operating system? Which version of handbrake-js?

**Comment by 75lb** [comment]
will re-open once I receive enough information to reproduce the issue.

**Comment by temitopeog** [comment]
Node version is v14.2.0
handbrake-js version is "^5.0.0". I experienced the same error as above

**Comment by 75lb** [comment]
I can't reproduce the issue.. which OS are you using? Can you post some code I can run to reproduce the issue? 

Have you tried reinstalling handbrake-js?

**Comment by temitopeog** [comment]
Its on Mac, angular application

**Comment by temitopeog** [comment]
hbjs.spawn({ input: file, output: 'something.mp4', preset : 'Normal' })
    .on('error', err => {
      console.log(err);
      // invalid user input, no video found etc
    })
    .on('progress', progress => {
      console.log(
        'Percent complete: %s, ETA: %s',
        progress.percentComplete,
        progress.eta
      );
    });

ok i'll reinstall the application and feedback

**Comment by 75lb** [comment]
This seems to be related to Angular config.. [see here](https://stackoverflow.com/questions/30000827/webpack-and-typescript-cannot-resolve-module-child-process-in-node-d-ts)
