### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by tsteer050** [75lb/handbrake-js#45]
Any success installing this on a Heroku project?  This buildpack seems to be the only thing out there that might allow it:

https://github.com/heroku/heroku-buildpack-apt

...but it doesn't appear to support the necessary commands.  Able to find the PPA when using the following in the Aptfile: 

:repo:deb http://ppa.launchpad.net/stebbins/handbrake-releases/ubuntu bionic main 

This results in an error for not having a public key.  Keys seem to only be supported via url, ex. https://nginx.org/keys/nginx_signing.key  

Not very experienced in this area, would appreciate any help.  Working perfectly in development

**Comment by 75lb** [comment]
Did you resolve this? If so, could you post the solution or close the issue? Thanks.
