### ISSUE TITLE
Electron application

### ISSUE THREAD

**Issue by majorgeek85** [75lb/handbrake-js#47]
Hi,

I have an electron and react application running on Windows 10. I added "handbrake-js": "4.0.1" to the package.json, run npm install, run the app and when it run hbjs.spawn it gives the error:

Error: HandbrakeCLI application not found: \bin\HandbrakeCLI.exe. Linux users must install HandbrakeCLI manually, please see https://handbrake.fr/downloads.php.
    at Handbrake._run (Handbrake.js:101)
    at index.js:54
    at process._tickCallback (internal/process/next_tick.js:61)

Shouldn't npm install be enough? The handbrake-js is in the node_modules.

Thanks

**Comment by 75lb** [comment]
hi, could you do me a favour please and tell me what value `process.platform` returns in your Electron app please? 

```js
console.log(process.platform)
```

**Comment by 75lb** [comment]
also, what does `process.arch` return?

**Comment by majorgeek85** [comment]
Sure,

process.platform returns = win32
and
process.arch = x64

I'm changing your code to try to debug the situation and it seems that while my electron app is running __dirname on config.js just resolves to \ and he tries to look for the .exe on c:\bin\HandbrakeCLI.exe instead of where it is. I can override your installation process and just put the .exe on another place and point to that, but I was trying not to if possible.

Thanks for your time.

**Comment by 75lb** [comment]
OK, thanks.. once you have settled on a solution feel free to send a PR showing your fix. I'll take a look and see how it can be incorporated.

**Comment by 75lb** [comment]
I will close this for now because there is nothing left for me to action. Once your electron app is stable please let me know what handbrake-js changes you needed to make, if any.
