### ISSUE TITLE
Question on license

### ISSUE THREAD

**Issue by Xan2063** [75lb/handbrake-js#49]
Hi,

we noticed that handbrake is released under the GPL v2, while handbrake.js uses MIT license. From my understanding the copyleft of the GPL v2 also applies to usages of handbrake.js. Please correct me, if I have a misunderstanding here.

Thanks

**Comment by 75lb** [comment]
Hi, the Handbrake licence (GPL) applies to work written by the Handbrake authors. It does not apply to my work. My work has an MIT licence, that is the only licence which applies to my work (handbrake-js).

**Comment by Xan2063** [comment]
Quoting wikipedia on [GPL](https://en.wikipedia.org/wiki/GNU_General_Public_License)
The GPL is a copyleft license, which means that derivative work must be open-source and distributed under the same license terms. This is in distinction to permissive free software licenses, of which the BSD licenses and the MIT License are widely-used less-restrictive examples. GPL was the first copyleft license for general use.
I'm not a license expert, I just want to make sure, we are not violating someones license by using your work

**Comment by 75lb** [comment]
> derivative work must be open-source and distributed under the same license terms

A "derivative work" means a fork or copy of Handbrake. My work (handbrake-js) is not a derivate work of Handbrake. It is a 100% separate body of work written in a different language (JS) for a different platform (node). Handbrake-js does include a distribution of the Handbrake binary which is permitted by the Handbrake [COPYING](https://github.com/HandBrake/HandBrake/blob/master/COPYING) licence.

I've added more licence info to the foot of the [readme](https://github.com/75lb/handbrake-js) and also the [licence](https://github.com/75lb/handbrake-js/blob/master/LICENSE). Let me know if it is still unclear.

**Comment by 75lb** [comment]
If you're still unclear, forward this conversation to the Handbrake team and ask them to verify everything is ok. Let me know how it goes.

**Comment by Xan2063** [comment]
Thank you, I will ask them and keep you informed

**Comment by Xan2063** [comment]
They also agree to your statement. See 
[here](https://github.com/HandBrake/HandBrake/issues/2442)

**Comment by 75lb** [comment]
good, thanks for letting me know @Xan2063 . 👍
