### ISSUE TITLE
Install on AWS Beanstalk

### ISSUE THREAD

**Issue by FlawaCLV** [75lb/handbrake-js#53]
I can't manage to make it work on AWS Elastic Beanstalk configured: **Node.js running on 64bit Amazon Linux/4.13.1**.

On the instance we only have access to `yum` and not `apt`. So this is not possible:

```bash
sudo add-apt-repository --yes ppa:stebbins/handbrake-releases
sudo apt-get update -qq
sudo apt-get install -qq handbrake-cli
```

Any idea on how to install the CLI on such an instance ?

**Comment by 75lb** [comment]
There's a Flatpak distribution on the [downloads page](https://handbrake.fr/downloads.php), you could try that.. More install docs [here](https://handbrake.fr/docs/en/1.3.0/get-handbrake/download-and-install.html).

**Comment by 75lb** [comment]
closing, since it's not an issue with this library..
