### ISSUE TITLE
Unable to user handbrake on windows 10

### ISSUE THREAD

**Issue by imhimanshujain** [75lb/handbrake-js#55]
Hi,
I was trying to covert webm video to mp4 using handbrake CLI in my windows 10 machine. But as soon as I run following command
`handbrake --input 'C:\Users\y13ug118\Downloads\input.webm' --output 'output.mp4' --preset Normal`
 it throws following message and exits.
`[14:58:16] Compile-time hardening features are enabled`

However same command is working in my windows 7 machine. Please help.

**Comment by 75lb** [comment]
Hi, does this post help: 
https://www.reddit.com/r/handbrake/comments/eqq6sz/unable_to_load_presets/
