### ISSUE TITLE
General Question: Where can I find a list of supported format (audio / video)

### ISSUE THREAD

**Issue by inglesuniversal** [75lb/handbrake-js#56]
I'm looking to convert 

FROM - TO
ogg - mp3
mkv - mp4
mov - mp4
avi - mp4

Thanks and stay SAFE

**Comment by 75lb** [comment]
This project (handbrake-js) is just a wrapper around HandbrakeCLI. You'll find all the docs about Handbrake on their website. 
https://handbrake.fr/features.php

Stay safe too!
