### ISSUE TITLE
Error: Cannot find module 'child_process' same as #42

### ISSUE THREAD

**Issue by temitopeog** [75lb/handbrake-js#57]
hbjs.spawn({ input: file, output: 'something.mp4', preset : 'Normal' })
    .on('error', err => {
      console.log(err);
      // invalid user input, no video found etc
    })
    .on('progress', progress => {
      console.log(
        'Percent complete: %s, ETA: %s',
        progress.percentComplete,
        progress.eta
      );
    });

Node version is v14.2.0
handbrake-js version is "^5.0.0". I experienced the same error as above

Thanks,
Temi

**Comment by 75lb** [comment]
Can you post the full error message including the stack trace? 

Please try deleting `node_modules` and `package-lock.json` and running `npm install` again from scratch.

**Comment by temitopeog** [comment]
will try now - thx

**Comment by temitopeog** [comment]
ERROR in ./node_modules/handbrake-js/index.js
Module not found: Error: Can't resolve 'child_process' in '/Users/.../Desktop/projects/bdylab/node_modules/handbrake-js'
ERROR in ./node_modules/handbrake-js/lib/Handbrake.js
Module not found: Error: Can't resolve 'child_process' in '/Users/..../Desktop/projects/bdylab/node_modules/handbrake-js/lib'

**Comment by temitopeog** [comment]
thats the full error message

**Comment by 75lb** [comment]
This sounds like an issue with the Angular build process.. `child_process` is built into Node.js, it will always be present.. please look into your build config..

**Comment by 75lb** [comment]
https://stackoverflow.com/questions/30000827/webpack-and-typescript-cannot-resolve-module-child-process-in-node-d-ts

**Comment by temitopeog** [comment]
thanks. i'll apply the above & get back to you.. much appreciated
