### ISSUE TITLE
error: Handbrake InitialisationError message : Cannot load libnvidia-encode.so

### ISSUE THREAD

**Issue by ankitmishra88** [75lb/handbrake-js#61]
I have installed handbrake-js on Ubuntu EC2 server with Node.js. Earlier It was working fine.But whenever now, I try to transcode a file to mp4, it gives following error:
{"status":false,"error":{"name":"Other","message":"Handbrake InitialisationError [error code: 3]","output":"Cannot load libnvidia-encode.so.1\nCannot load libnvidia-encode.so.1\nCannot load libnvidia-encode.so.1\nCannot load libnvidia-encode.so.1\n[08:37:44] hb_init: starting libhb thread\n[08:37:44] thread 7f7eb5df1700 started (\"libhb\")\nHandBrake 1.2.1 (2019021900) - Linux x86_64........................................ }
It's a long list. 
So what may be the possible solution? Earlier it was working fine.

**Comment by 75lb** [comment]
Hi.. this error is related to the underlying `HandbrakeCLI` binary, not the handbrake-js wrapper library.. have you tried reinstalling the handbrake Linux package? Something seems corrupted..

**Comment by ankitmishra88** [comment]
Ok, so I haven't reinstalled Handbrake CLI, I try reinstalling and see if it works. Thanks

**Comment by ankitmishra88** [comment]
I removed and installed handbrake-cli, but error is still there. You can see the error in below screenshot of console. 
![Screenshot (52)](https://user-images.githubusercontent.com/42653549/104349333-ccebf280-5528-11eb-8497-86309746e6b6.png)

**Comment by 75lb** [comment]
ok, this is not an issue with the handbrake-js wrapper library, which is doing its job correctly.. please try running handbrake directly (not the handbrake-js Node.js library) - if it also fails with handbrake directly, you need to contact handbrake..

**Comment by ankitmishra88** [comment]
Thanks, I checked running HandbrakeCLI from terminal directly without Node.JS library, It works only with sudo. This may be the issue? To make it work with Node.js, what should I do?

**Comment by 75lb** [comment]
then you must also run `node` with sudo..

**Comment by ankitmishra88** [comment]
Oh yes, thanks 👍
