### ISSUE TITLE
Not able to extract audio from video

### ISSUE THREAD

**Issue by donny08** [75lb/handbrake-js#64]
I am using handbrake-js to convert the mkv video file to mp3. Output mp3 file has no audio

OS: MAC

Below code:
```
const hbjs = require('handbrake-js');

hbjs.spawn({ input: 'sample_960x400_ocean_with_audio.mkv', output: 'test.mp3' })
  .on('error', err => {
    // invalid user input, no video found etc
    console.log(err)
  })
  .on('progress', progress => {
    console.log(
      'Percent complete: %s, ETA: %s',
      progress.percentComplete,
      progress.eta
    )
  });
```

**Comment by 75lb** [comment]
does the encode work correctly when using the Handbrake UI?

**Comment by 75lb** [comment]
For questions with Handbrake itself and encoding in general, the Official Handbrake forum is your best bet
https://forum.handbrake.fr/
