### ISSUE TITLE
can .spawn also encode audio files?

### ISSUE THREAD

**Issue by Nitzahon** [75lb/handbrake-js#65]
I've been using .spawn() to reencode video files from the server before I concat them.  A new use case has arisen where sometimes it needs to be audio files instead of video files, and I don't want to write a whole new block of code for that case, rather just dynamically choose the file extension based on the file.contentType.  when I tried using spawn with a .weba file, I got the following error: InvalidInput: Invalid input, not a video file [error code: 2].

**Comment by 75lb** [comment]
This repo is for the Javascript wrapper of Handbrake, not for Handbrake itself.. For questions about Handbrake and encoding in general, the official forum is your best bet!
https://forum.handbrake.fr/
