### ISSUE TITLE
Upgrade handbrake-js to use the latest version of HandbrakeCLI

### ISSUE THREAD

**Issue by 75lb** [75lb/handbrake-js#67]
We should upgrade handbrake-js to use [the latest HandbrakeCLI](https://github.com/HandBrake/HandBrake/releases).

Since we're upgrading from HandbrakeCLI v1.3 to v1.5 there will be a high risk of breaking changes, so this update will be released in a new major version of handbrake-js.

To implement:

* [ ] Update [this version number](https://github.com/75lb/handbrake-js/blob/master/scripts/install.js#L13) to the latest available.
* [ ] Check you have deleted your local `./bin/HandbrakeCLI`. 
* [ ] Run `./script/install.js` to download and install the latest HandbrakeCLI
* [ ] Run `npm test` and do some test encodes locally.
* [ ] Submit PR

**Comment by ryuuskylark** [comment]
I've been using the v1.5.1 for a couple of encodes lately, nothing out of the ordinary, basic functionality of the spawn, run and exec all see to work as expected thus far...

Mostly used to convert using a preset import file, I did have issues with the `HandbrakeCLIPath`, I have made a pull request #74 to address the issue I had, feel free to review it, and\or deny it.

Just some 2 cent commentary.
