### ISSUE TITLE
Error while installing on AWS Bitnami LAMP - NodeJS Server

### ISSUE THREAD

**Issue by inglesuniversal** [75lb/handbrake-js#69]
Hello... I got this error... Any ideas?

     npm install -g handbrake.js
     npm ERR! code E404
     npm ERR! 404 Not Found - GET https://registry.npmjs.org/handbrake.js - Not found
     npm ERR! 404 
     npm ERR! 404  'handbrake.js@*' is not in the npm registry.
     npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
     npm ERR! 404 
     npm ERR! 404 Note that you can also install from a
     npm ERR! 404 tarball, folder, http url, or git url.

     npm ERR! A complete log of this run can be found in:
     npm ERR!     /home/bitnami/.npm/_logs/2021-10-09T18_57_20_415Z-debug.log

Hope this log helps

Regards

**Comment by 75lb** [comment]
typo... it's "handbrake-js" not "handbrake.js".
