### ISSUE TITLE
The path is being pass to the cli options

### ISSUE THREAD

**Issue by ethoslabmx** [75lb/handbrake-js#77]
If using HandbrakeCLIPath, that is being pass to the cli options and an error is return for unknown option

**Comment by 75lb** [comment]
Hi, could you post a reproduction case please - some code I can run to see your issue.

**Comment by 75lb** [comment]
never mind - I have reproduced it.. looking into it..

**Comment by 75lb** [comment]
[Fixed in v7.1.0](https://github.com/75lb/handbrake-js/releases/tag/v7.1.0), let me know if you find anything else.. thanks.
