### ISSUE TITLE
HandBrake audion and video issues

### ISSUE THREAD

**Issue by ZaidJaveed** [75lb/handbrake-js#78]
I tried encoding a video using handBrake, i was successfully able to encode the video. However the encoded video has no audio, also it is not specified in documentation as well how to specify audio codec options and how to improve viode quality

**Comment by 75lb** [comment]
Hi, this module is a Javasript wrapper around the `HandbrakeCLI` tool - [see here for Handbrake documentation](https://handbrake.fr/docs/en/1.6.0/cli/command-line-reference.html).

If you find a bug in this handbrake-js wrapper, please let me know with some failing code I can run to reproduce the issue.
